version: '3'
networks:
  watch_store_default:
    external: true
services:
  loopbackapi:
    build: 
      context: .
      dockerfile: Dockerfile
    image: node:16
    networks:
      - watch_store_default
    ports:
      - 3000:3000
    restart: always
  minio:
    image: minio/minio
    environment:
      MINIO_CONSOLE_ADDRESS: :9090
    command: server /data
    networks:
      - watch_store_default
    ports:
      - "9090:9090"
      - "9000:9000"
      - "9001:9001"
    restart: always