version: '3'
networks:
  watch_store_default:
    external: true
services:
  loopbackapi:
    build: 
      context: .
      dockerfile: Dockerfile
    image: node:16
    networks:
      - watch_store_default
    ports:
      - 3000:3000
    restart: always
    